# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    name: Run CI
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name : Check style code
        run : |
          sudo apt-get install -y cppcheck
          cppcheck --enable=all --enable=warning,style,performance,portability --suppress=missingIncludeSystem . # --check-config

      - name : Building
        run : |
          mkdir build
          cd build
          sudo apt-get install -y libgtest-dev
          cmake ..
          make
          cd ..

#      - name: Coverage one-thread-mode test
#        run: |
#          sudo apt-get install lcov
#          ./build/test_matrix_one_thread.out
#          mkdir coverage && cd coverage
#          gcov ../build/CMakeFiles/lib_matrix_one_thread.dir/project/src/matrix_one_thread.c.o
#          cp -r ../build/CMakeFiles/lib_matrix_one_thread.dir/ .
#          cd ..
#          lcov --capture --directory coverage/ --output-file matrix_one_thread.info
#          genhtml matrix_one_thread.info --output-directory coverage-report/

      - name: Archive coverage test results
        uses: actions/upload-artifact@v2
        with:
          name: Coverage test
          path: coverage-report/

      - name: Valgrind test
        run: |
          sudo apt-get install -y valgrind
          mkdir valgrid-output
          valgrind --leak-check=full --tool=memcheck --show-leak-kinds=all --log-file=valgrid-output/report -q ./build/test_matrix_one_thread.out
          valgrind --leak-check=full --tool=memcheck --show-leak-kinds=all --log-file=valgrid-output/report -q ./build/test_matrix_multi_thread.out
          valgrind --leak-check=full --tool=memcheck --show-leak-kinds=all --log-file=valgrid-output/report -q ./build/stress_test.out

      - name: Archive valgrind test results
        uses: actions/upload-artifact@v2
        with:
          name: Valgrind test
          path: valgrid-output/